#!/bin/bash

#Update e Upgrade
#sudo apk update
#sudo apk upgrade

#Apps
#sudo apk add neofetch net-tools btop

#Copiar Chave SSH Ansible
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuHkj1l6mn3cWQr+Nt4sVyQGsOr9DOdDqYSj9ajP+MHakmTneJsUmu9KGUu1pc5QJcdzQEsM3G5a8XMcdpe7xATSyje9Sewwsgo6n/SrUqSX61PSxymwxhPU75VYxLpk9/JjCS2DeZzkyRIx+OWDlAzXC64rCeuWEMZ2fzoCr8AIc3rNU3/maGU1rtRQ2WSQVuKp6kvgQ/O9dP3toY84BRJGtmw24eeHmHckO2voEEZZBWLv6+buPusCd+dldZkK5RGG9kZ7EU9A+QnbfU78NBhfZH4Q+1EdFPvhK9fKjtPDlTMLk01YXO4pOCivPSxOvlpO6fXlibbknnEuFg5EssSxtXtWIlSeW18ltTOj1/buynfuOfMNDSvAx1TYhOkeLGcjtRazHvTeqqy2jjsCxoMOnO/F/FFUXMzK/G9eHyHT+DVyAukCUpGsOtKgtny+58zYmkkrCEZ6Hr4ClTZsKD5UlfkHeKHiIDjChYm9K2YUsmqUAIVh0yknOqMNaixAM= root@master" >> /home/vagrant/.ssh/authorized_keys