# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "master" => {"memory" => "1024", "cpu" => "2", "ip" => "100", "image" => "generic/debian12"},
  "node01" => {"memory" => "1024", "cpu" => "2", "ip" => "101", "image" => "generic/debian12"},
  "node02" => {"memory" => "1024", "cpu" => "2", "ip" => "102", "image" => "generic/debian12"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "10.0.0.#{conf["ip"]}"
      machine.vm.provider "libvirt" do |vb|
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
      end
 
      machine.vm.provision "shell", path: "geral.sh"
 
#      if "#{name}" == "master"
#        machine.vm.provision "shell", path: "master.sh"
#     end
 
    end
  end
end